### 1.1 Créer une liste Python

**Objectif :**
Stocker les températures mesurées par un capteur dans une liste Python.

Les températures sont :

`24.5, 25.1, 26.3, 27.0, 25.8`


In [45]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]

print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 1.2 Créer un tableau NumPy

**Objectif :**
Créer un tableau NumPy contenant les mêmes températures que la liste Python précédente.


In [46]:
import numpy as np

temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

print(temperatures_numpy)

[24.5 25.1 26.3 27.  25.8]


### 1.3 Multiplier les collections par 2

**Objectif :**
Observer le comportement d'une multiplication par 2 sur une liste Python et sur un tableau NumPy.


In [47]:
temperatures_liste_fois_2 = temperatures_liste * 2
temperatures_numpy_fois_2 = temperatures_numpy * 2

print("Liste Python :", temperatures_liste_fois_2)
print("Tableau NumPy :", temperatures_numpy_fois_2)

Liste Python : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Tableau NumPy : [49.  50.2 52.6 54.  51.6]


### 1.4 Différence entre une liste Python et un tableau NumPy

**Observation :**

Avec une liste Python :

```text
[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
```

La multiplication par `2` **répète la liste deux fois**.

Avec NumPy :

```text
[49.  50.2 52.6 54.  51.6]
```

La multiplication par `2` **multiplie chaque valeur par 2**.

**Conclusion :**

Une liste Python et un tableau NumPy n'ont donc pas le même comportement avec l'opérateur `*`. NumPy permet notamment d'effectuer directement des opérations numériques sur l'ensemble des valeurs du tableau.


### 2.1 Créer un tableau de 10 capteurs

**Objectif :**
Créer un tableau représentant les mesures de 10 capteurs, avec une valeur initiale de `0`.


In [48]:
temperatures_capteurs = np.zeros(10)

print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2.2 Créer un tableau de valeurs égales à 1

**Objectif :**
Créer un tableau contenant 10 valeurs égales à `1`.


In [49]:
valeurs_un = np.ones(10)

print(valeurs_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 2.3 Créer un tableau initialisé à 25

**Objectif :**
Créer un tableau contenant 10 valeurs initialisées à `25`.


In [50]:
temperatures_initiales = np.full(10, 25)

print(temperatures_initiales)

[25 25 25 25 25 25 25 25 25 25]


### 2.4 Créer une matrice identité

**Objectif :**
Créer une matrice identité de taille `5 × 5`.


In [51]:
matrice_identite = np.eye(5)

print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 2.5 Créer les 24 heures

**Objectif :**
Créer les heures d'une journée, de `0` à `23`.


In [52]:
heures = np.arange(24)

print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 2.6 Créer des températures régulièrement réparties

**Objectif :**
Créer 10 valeurs régulièrement réparties entre `20 °C` et `30 °C`.


In [53]:
temperatures_regulieres = np.linspace(20, 30, 10)

print(temperatures_regulieres)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 2.7 Générer des températures aléatoires

**Objectif :**
Générer aléatoirement 100 températures tout en rendant les résultats reproductibles.

La graine permet d'obtenir les mêmes valeurs à chaque exécution.


In [54]:
np.random.seed(42)

temperatures_aleatoires = np.random.uniform(20, 30, 100)

print(temperatures_aleatoires)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

### 3.1 Créer aléatoirement les températures d'une journée

**Objectif :**
Créer aléatoirement un tableau contenant les 24 températures mesurées pendant une journée.


In [55]:
temperatures_journee = np.random.uniform(20, 30, 24)

print(temperatures_journee)

[20.31429186 26.36410411 23.14355981 25.08570691 29.07566474 22.49292229
 24.10382923 27.55551139 22.28798165 20.7697991  22.89751453 21.61221287
 29.29697652 28.0812038  26.33403757 28.7146059  28.03672077 21.86570059
 28.92558998 25.39342242 28.07440155 28.960913   23.18003475 21.10051925]


### 3.2 a) Déterminer le nombre de dimensions

**Objectif :**
Déterminer le nombre de dimensions du tableau.

La propriété `ndim` indique le nombre de dimensions d'un tableau NumPy.


In [56]:
print("Nombre de dimensions :", temperatures_journee.ndim)

Nombre de dimensions : 1


### 3.2 b) Déterminer le nombre de valeurs

**Objectif :**
Déterminer combien de valeurs contient le tableau.

La propriété `size` donne le nombre total d'éléments.


In [57]:
print("Nombre de valeurs :", temperatures_journee.size)

Nombre de valeurs : 24


### 3.2 c) Déterminer le type des données

**Objectif :**
Identifier le type des valeurs stockées dans le tableau.

La propriété `dtype` indique le type des données.


In [58]:
print("Type des données :", temperatures_journee.dtype)

Type des données : float64


### 3.2 d) Déterminer la forme du tableau

**Objectif :**
Déterminer la forme du tableau.

La propriété `shape` indique la taille du tableau selon chacune de ses dimensions.


In [59]:
print("Forme du tableau :", temperatures_journee.shape)

Forme du tableau : (24,)


### 4.1 Afficher la première mesure

**Objectif :**
Accéder à la première température du tableau.

En NumPy, l'index `0` correspond au premier élément.


In [60]:
print("Première mesure :", temperatures_journee[0])

Première mesure : 20.314291856867342


### 4.2 Afficher la dernière mesure

**Objectif :**
Accéder à la dernière température du tableau.

L'index `-1` permet d'accéder au dernier élément.


In [61]:
print("Dernière mesure :", temperatures_journee[-1])

Dernière mesure : 21.100519245276768


### 4.3 Afficher la température de 8h

**Objectif :**
Afficher la température mesurée à 8h.

Puisque les heures commencent à `0`, l'heure `8` correspond à l'index `8`.


In [62]:
print("Température à 8h :", temperatures_journee[8])

Température à 8h : 22.287981654916223


### 4.4 Afficher les températures de 8h à 12h

**Objectif :**
Extraire les températures mesurées de 8h à 12h.

Avec le slicing, la borne de fin est exclue. Il faut donc utiliser `13` pour inclure la mesure de 12h.


In [63]:
print("Températures de 8h à 12h :", temperatures_journee[8:13])

Températures de 8h à 12h : [22.28798165 20.7697991  22.89751453 21.61221287 29.29697652]


### 4.5 Afficher les 6 premières températures

**Objectif :**
Extraire les températures correspondant aux 6 premières heures de la journée.


In [64]:
print("6 premières heures :", temperatures_journee[:6])

6 premières heures : [20.31429186 26.36410411 23.14355981 25.08570691 29.07566474 22.49292229]


### 4.6 Afficher les températures des heures paires

**Objectif :**
Extraire les températures correspondant aux heures paires : `0, 2, 4, ..., 22`.

Le slicing utilise ici un pas de `2`.


In [65]:
print("Températures des heures paires :", temperatures_journee[::2])

Températures des heures paires : [20.31429186 23.14355981 29.07566474 24.10382923 22.28798165 22.89751453
 29.29697652 26.33403757 28.03672077 28.92558998 28.07440155 23.18003475]


### 5.1 Afficher les températures supérieures à 30 °C

**Objectif :**
Détecter les températures dépassant `30 °C`.

Le filtrage booléen permet de sélectionner uniquement les valeurs qui respectent une condition.


In [66]:
temperatures_superieures_30 = temperatures_journee[temperatures_journee > 30]

print("Températures supérieures à 30 °C :", temperatures_superieures_30)

Températures supérieures à 30 °C : []


### 5.2 Afficher les températures normales

**Objectif :**
Afficher les températures comprises entre `20 °C` et `30 °C`.

On utilise deux conditions combinées avec `&`.


In [67]:
temperatures_normales = temperatures_journee[
    (temperatures_journee >= 20) & (temperatures_journee <= 30)
]

print("Températures normales :", temperatures_normales)

Températures normales : [20.31429186 26.36410411 23.14355981 25.08570691 29.07566474 22.49292229
 24.10382923 27.55551139 22.28798165 20.7697991  22.89751453 21.61221287
 29.29697652 28.0812038  26.33403757 28.7146059  28.03672077 21.86570059
 28.92558998 25.39342242 28.07440155 28.960913   23.18003475 21.10051925]


### 5.3 Déterminer les températures anormales

**Objectif :**
Créer un tableau booléen indiquant quelles températures sont supérieures à `35 °C`.

`True` indique une anomalie et `False` une température normale.


In [68]:
anomalies = temperatures_journee > 35

print("Anomalies :", anomalies)

Anomalies : [False False False False False False False False False False False False
 False False False False False False False False False False False False]


### 5.4 Déterminer le nombre d'anomalies

**Objectif :**
Compter le nombre de températures considérées comme anormales à partir du tableau booléen `anomalies`.

Dans NumPy, les valeurs `True` sont comptées comme `1` et les valeurs `False` comme `0`.


In [69]:
nombre_anomalies = np.sum(anomalies)

print("Nombre de températures anormales :", nombre_anomalies)

Nombre de températures anormales : 0


### 6.1 Créer la matrice des températures

**Objectif :**
Créer aléatoirement la matrice représentant les températures mesurées par 5 capteurs pendant une journée.

Chaque ligne représente un capteur et chaque colonne représente une heure.


In [70]:
temperatures_capteurs_journee = np.random.uniform(20, 30, (5, 24))

print(temperatures_capteurs_journee)

[[22.27935163 24.27107789 28.18014766 28.60730583 20.06952131 25.10747303
  24.17411003 22.2210781  21.19865367 23.37615171 29.42909704 23.23202932
  25.18790622 27.03018959 23.63629602 29.71782083 29.62447295 22.51782296
  24.97248506 23.0087831  22.84840494 20.36886947 26.09564334 25.02679023]
 [20.51478751 22.78646464 29.08265886 22.39561891 21.44894872 24.8945276
  29.85650454 22.42055272 26.72135547 27.61619615 22.37637544 27.28216349
  23.67783133 26.32305831 26.33529711 25.35774684 20.9028977  28.35302496
  23.20780065 21.8651851  20.40775142 25.90892943 26.77564362 20.16587829]
 [25.12093058 22.26495775 26.4517279  21.74366429 26.90937738 23.86735346
  29.36729989 21.37520944 23.41066351 21.13473521 29.24693618 28.77339353
  22.57941628 26.59984046 28.172222   25.55200812 25.29650578 22.41852291
  20.93102768 28.97215758 29.00418057 26.33101457 23.39029791 23.49209575]
 [27.25955679 28.9711026  28.87086424 27.79875546 26.42031646 20.84139965
  21.61628714 28.98554189 26.0642906

### 6.2 Aplatir la matrice

**Objectif :**
Transformer la matrice des températures en un tableau unidimensionnel.

La méthode `flatten()` crée une copie aplatie du tableau.


In [71]:
temperatures_aplaties = temperatures_capteurs_journee.flatten()

print(temperatures_aplaties)

[22.27935163 24.27107789 28.18014766 28.60730583 20.06952131 25.10747303
 24.17411003 22.2210781  21.19865367 23.37615171 29.42909704 23.23202932
 25.18790622 27.03018959 23.63629602 29.71782083 29.62447295 22.51782296
 24.97248506 23.0087831  22.84840494 20.36886947 26.09564334 25.02679023
 20.51478751 22.78646464 29.08265886 22.39561891 21.44894872 24.8945276
 29.85650454 22.42055272 26.72135547 27.61619615 22.37637544 27.28216349
 23.67783133 26.32305831 26.33529711 25.35774684 20.9028977  28.35302496
 23.20780065 21.8651851  20.40775142 25.90892943 26.77564362 20.16587829
 25.12093058 22.26495775 26.4517279  21.74366429 26.90937738 23.86735346
 29.36729989 21.37520944 23.41066351 21.13473521 29.24693618 28.77339353
 22.57941628 26.59984046 28.172222   25.55200812 25.29650578 22.41852291
 20.93102768 28.97215758 29.00418057 26.33101457 23.39029791 23.49209575
 27.25955679 28.9711026  28.87086424 27.79875546 26.42031646 20.84139965
 21.61628714 28.98554189 26.0642906  20.09197052 21.

### 6.3 Déterminer la transposée de la matrice

**Objectif :**
Inverser les lignes et les colonnes de la matrice.

La transposée transforme une matrice de forme `(5, 24)` en une matrice de forme `(24, 5)`.


In [72]:
temperatures_transposees = temperatures_capteurs_journee.T

print(temperatures_transposees)

[[22.27935163 20.51478751 25.12093058 27.25955679 26.57612892]
 [24.27107789 22.78646464 22.26495775 28.9711026  25.68308603]
 [28.18014766 29.08265886 26.4517279  28.87086424 20.93674768]
 [28.60730583 22.39561891 21.74366429 27.79875546 23.67715803]
 [20.06952131 21.44894872 26.90937738 26.42031646 22.65202368]
 [25.10747303 24.8945276  23.86735346 20.84139965 22.43989643]
 [24.17411003 29.85650454 29.36729989 21.61628714 29.73010555]
 [22.2210781  22.42055272 21.37520944 28.98554189 23.93097725]
 [21.19865367 26.72135547 23.41066351 26.0642906  28.92046555]
 [23.37615171 27.61619615 21.13473521 20.09197052 26.31138626]
 [29.42909704 22.37637544 29.24693618 21.01471543 27.94811304]
 [23.23202932 27.28216349 28.77339353 26.63501769 25.02637093]
 [25.18790622 23.67783133 22.57941628 20.05061584 25.76903885]
 [27.03018959 26.32305831 26.59984046 21.60808051 24.92517694]
 [23.63629602 26.33529711 28.172222   25.48733789 21.95242988]
 [29.71782083 25.35774684 25.55200812 26.91895198 27.22

### 6.4 Extraire les mesures du capteur 1

**Objectif :**
Extraire toutes les mesures enregistrées par le premier capteur pendant la journée.

Le premier capteur correspond à la première ligne de la matrice.


In [73]:
capteur_1 = temperatures_capteurs_journee[0]

print("Mesures du capteur 1 :", capteur_1)

Mesures du capteur 1 : [22.27935163 24.27107789 28.18014766 28.60730583 20.06952131 25.10747303
 24.17411003 22.2210781  21.19865367 23.37615171 29.42909704 23.23202932
 25.18790622 27.03018959 23.63629602 29.71782083 29.62447295 22.51782296
 24.97248506 23.0087831  22.84840494 20.36886947 26.09564334 25.02679023]


### 6.5 Extraire les mesures du capteur 5

**Objectif :**
Extraire toutes les mesures enregistrées par le cinquième capteur.

Le cinquième capteur correspond à l'index `4`.


In [74]:
capteur_5 = temperatures_capteurs_journee[4]

print("Mesures du capteur 5 :", capteur_5)

Mesures du capteur 5 : [26.57612892 25.68308603 20.93674768 23.67715803 22.65202368 22.43989643
 29.73010555 23.93097725 28.92046555 26.31138626 27.94811304 25.02637093
 25.76903885 24.92517694 21.95242988 27.22452115 22.80772362 20.24315966
 26.45472296 21.77110679 29.40458584 29.53928577 29.1486439  23.701587  ]


### 6.6 Extraire les mesures de 10h

**Objectif :**
Extraire la température enregistrée par chacun des 5 capteurs à `10h`.

L'heure `10` correspond à la colonne d'index `10`.

In [75]:
temperatures_10h = temperatures_capteurs_journee[:, 10]

print("Mesures de tous les capteurs à 10h :", temperatures_10h)

Mesures de tous les capteurs à 10h : [29.42909704 22.37637544 29.24693618 21.01471543 27.94811304]


### 6.7 Extraire les mesures des capteurs 2 à 4

**Objectif :**
Extraire les mesures des capteurs `2`, `3` et `4`, entre `8h` et `12h` inclus.

Les capteurs 2 à 4 correspondent aux lignes `1` à `3`, et les heures 8 à 12 aux colonnes `8` à `12`.


In [76]:
temperatures_capteurs_2_4 = temperatures_capteurs_journee[1:4, 8:13]

print("Mesures des capteurs 2 à 4 entre 8h et 12h :")
print(temperatures_capteurs_2_4)

Mesures des capteurs 2 à 4 entre 8h et 12h :
[[26.72135547 27.61619615 22.37637544 27.28216349 23.67783133]
 [23.41066351 21.13473521 29.24693618 28.77339353 22.57941628]
 [26.0642906  20.09197052 21.01471543 26.63501769 20.05061584]]


### 7.1 Créer les températures du deuxième bâtiment

**Objectif :**
Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs du deuxième bâtiment durant une journée.


In [77]:
temperatures_batiment_2 = np.random.uniform(20, 30, (3, 24))

print(temperatures_batiment_2)

[[20.15456617 29.28318563 24.28184148 29.66654819 29.63619977 28.53009455
  22.94448892 23.85097729 28.51136672 23.16922005 21.69492747 25.56801262
  29.36154774 26.96029797 25.7006117  20.97176494 26.15007227 29.9005385
  21.40084015 25.18329652 28.77373072 27.40768618 26.97015741 27.02484084]
 [23.59491151 22.93591844 28.09361155 28.10113395 28.67072319 29.13240553
  25.11342399 25.01516295 27.98295179 26.49963931 27.01966877 27.95792669
  28.90005342 23.37995157 23.75582953 20.9398194  25.78280141 20.35942274
  24.65598018 25.42644635 22.86541252 25.90833261 20.3050025  20.37348189]
 [28.22600561 23.60190641 21.27060513 25.2224326  27.69993553 22.15821027
  26.22890476 20.85347465 20.51681721 25.31354632 25.40635122 26.37429901
  27.26091334 29.75852079 25.16300348 23.22956473 27.95186195 22.70832251
  24.38971421 20.78456381 20.25350743 29.62648415 28.35980121 26.95974206]]


### 7.2 Fusionner les deux bâtiments avec `np.concatenate()`

**Objectif :**
Fusionner les données des 5 capteurs du premier bâtiment et des 3 capteurs du deuxième bâtiment.

Avec `axis=0`, on ajoute les lignes du deuxième bâtiment sous celles du premier.


In [78]:
temperatures_8_capteurs = np.concatenate(
    (temperatures_capteurs_journee, temperatures_batiment_2),
    axis=0
)

print(temperatures_8_capteurs)

[[22.27935163 24.27107789 28.18014766 28.60730583 20.06952131 25.10747303
  24.17411003 22.2210781  21.19865367 23.37615171 29.42909704 23.23202932
  25.18790622 27.03018959 23.63629602 29.71782083 29.62447295 22.51782296
  24.97248506 23.0087831  22.84840494 20.36886947 26.09564334 25.02679023]
 [20.51478751 22.78646464 29.08265886 22.39561891 21.44894872 24.8945276
  29.85650454 22.42055272 26.72135547 27.61619615 22.37637544 27.28216349
  23.67783133 26.32305831 26.33529711 25.35774684 20.9028977  28.35302496
  23.20780065 21.8651851  20.40775142 25.90892943 26.77564362 20.16587829]
 [25.12093058 22.26495775 26.4517279  21.74366429 26.90937738 23.86735346
  29.36729989 21.37520944 23.41066351 21.13473521 29.24693618 28.77339353
  22.57941628 26.59984046 28.172222   25.55200812 25.29650578 22.41852291
  20.93102768 28.97215758 29.00418057 26.33101457 23.39029791 23.49209575]
 [27.25955679 28.9711026  28.87086424 27.79875546 26.42031646 20.84139965
  21.61628714 28.98554189 26.0642906

### 7.(3) Fusionner les deux bâtiments avec `np.vstack()`

**Objectif :**
Réaliser la même fusion en utilisant une deuxième méthode.

`np.vstack()` empile les tableaux verticalement.


In [79]:
temperatures_8_capteurs_vstack = np.vstack(
    (temperatures_capteurs_journee, temperatures_batiment_2)
)

print(temperatures_8_capteurs_vstack)

[[22.27935163 24.27107789 28.18014766 28.60730583 20.06952131 25.10747303
  24.17411003 22.2210781  21.19865367 23.37615171 29.42909704 23.23202932
  25.18790622 27.03018959 23.63629602 29.71782083 29.62447295 22.51782296
  24.97248506 23.0087831  22.84840494 20.36886947 26.09564334 25.02679023]
 [20.51478751 22.78646464 29.08265886 22.39561891 21.44894872 24.8945276
  29.85650454 22.42055272 26.72135547 27.61619615 22.37637544 27.28216349
  23.67783133 26.32305831 26.33529711 25.35774684 20.9028977  28.35302496
  23.20780065 21.8651851  20.40775142 25.90892943 26.77564362 20.16587829]
 [25.12093058 22.26495775 26.4517279  21.74366429 26.90937738 23.86735346
  29.36729989 21.37520944 23.41066351 21.13473521 29.24693618 28.77339353
  22.57941628 26.59984046 28.172222   25.55200812 25.29650578 22.41852291
  20.93102768 28.97215758 29.00418057 26.33101457 23.39029791 23.49209575]
 [27.25955679 28.9711026  28.87086424 27.79875546 26.42031646 20.84139965
  21.61628714 28.98554189 26.0642906

### 8.1 Calculer les statistiques des températures

**Objectif :**
Calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l'écart-type des températures du premier bâtiment.


In [80]:
minimum = np.min(temperatures_journee)
maximum = np.max(temperatures_journee)
somme = np.sum(temperatures_journee)
moyenne = np.mean(temperatures_journee)
mediane = np.median(temperatures_journee)
variance = np.var(temperatures_journee)
ecart_type = np.std(temperatures_journee)

print("Minimum :", minimum)
print("Maximum :", maximum)
print("Somme :", somme)
print("Moyenne :", moyenne)
print("Médiane :", mediane)
print("Variance :", variance)
print("Écart-type :", ecart_type)

Minimum : 20.314291856867342
Maximum : 29.29697652342573
Somme : 603.6672245871639
Moyenne : 25.152801024465163
Médiane : 25.23956466540177
Variance : 9.162198107086189
Écart-type : 3.0269123058136636


### 8.2 Standardiser le tableau

**Objectif :**
Standardiser les températures afin d'obtenir un tableau dont la moyenne est proche de `0` et l'écart-type proche de `1`.

La formule utilisée est :

`z = (x - moyenne) / écart-type`


In [81]:
temperatures_standardisees = (
    (temperatures_journee - np.mean(temperatures_journee))
    / np.std(temperatures_journee)
)

print("Températures standardisées :")
print(temperatures_standardisees)

Températures standardisées :
[-1.59849665  0.40017779 -0.66379234 -0.02216586  1.29599517 -0.87874324
 -0.34654846  0.79378261 -0.94644941 -1.44801087 -0.74507824 -1.16970292
  1.36910987  0.96745544  0.39024472  1.17671228  0.9527596  -1.08595826
  1.24641502  0.07949401  0.96520818  1.25808467 -0.65174213 -1.33875097]


In [82]:
print("Moyenne :", np.mean(temperatures_standardisees))
print("Écart-type :", np.std(temperatures_standardisees))

Moyenne : -5.921189464667501e-16
Écart-type : 0.9999999999999998


### 8.3 Normaliser les températures

**Objectif :**
Ramener les températures dans l'intervalle `[0, 1]` grâce à la normalisation Min-Max.

La formule utilisée est :

`x_normalise = (x - minimum) / (maximum - minimum)`


In [83]:
temperatures_normalisees = (
    (temperatures_journee - np.min(temperatures_journee))
    / (np.max(temperatures_journee) - np.min(temperatures_journee))
)

print("Températures normalisées :")
print(temperatures_normalisees)

Températures normalisées :
[0.         0.67349712 0.31496908 0.53117918 0.9753624  0.24253667
 0.42187136 0.80613088 0.21972159 0.05070948 0.28757802 0.14449144
 1.         0.86465375 0.67014995 0.93516742 0.85970166 0.17271103
 0.95865528 0.5654357  0.86389648 0.96258763 0.31902967 0.08752699]


In [84]:
print("Minimum :", np.min(temperatures_normalisees))
print("Maximum :", np.max(temperatures_normalisees))

Minimum : 0.0
Maximum : 1.0


### 8.4 Convertir les températures en Fahrenheit

**Objectif :**
Convertir les températures du tableau initial de degrés Celsius en degrés Fahrenheit.

La formule utilisée est :

`F = C × 9/5 + 32`


In [85]:
temperatures_fahrenheit = temperatures_journee * 9 / 5 + 32

print("Températures en Fahrenheit :")
print(temperatures_fahrenheit)

Températures en Fahrenheit :
[68.56572534 79.4553874  73.65840766 77.15427244 84.33619653 72.48726012
 75.38689261 81.59992049 72.11836698 69.38563838 73.21552615 70.90198317
 84.73455774 82.54616683 79.40126762 83.68629062 82.46609738 71.35826106
 84.06606197 77.70816035 82.53392279 84.1296434  73.72406255 69.98093464]


### 9.1 Créer la matrice `temperatures_3x3`

**Objectif :**
Créer aléatoirement une matrice `3 × 3` représentant les températures mesurées par les 3 capteurs à 10h, 11h et 12h dans le 2nd batiment.

In [86]:
temperatures_3x3 = np.random.uniform(20, 30, (3, 3))

print("Températures mesurées :")
print(temperatures_3x3)

Températures mesurées :
[[24.08952944 21.7329432  21.56437043]
 [22.50242898 25.49226665 27.14595923]
 [26.60197377 22.79933897 29.54865281]]


### 9.2 Appliquer les corrections avec le Broadcasting

**Objectif :**
Appliquer automatiquement une correction propre à chaque capteur.

Le tableau `correction` contient une valeur pour chacun des 3 capteurs. NumPy applique automatiquement ces corrections aux lignes correspondantes grâce au Broadcasting.


In [87]:
correction = np.array([1, -0.5, 0.2])

mesures_corrigees = temperatures_3x3 + correction

print("Mesures corrigées :")
print(mesures_corrigees)

Mesures corrigées :
[[25.08952944 21.2329432  21.76437043]
 [23.50242898 24.99226665 27.34595923]
 [27.60197377 22.29933897 29.74865281]]
